name: CI & Publish

on:
  push: # Tests will trigger when and branch is pushed to
  pull_request:

jobs:
  test:
    name: Test on ${{ matrix.os }} / Python ${{ matrix.python-version }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.12"]
    env:
      NOSIBLE_API_KEY: ${{ secrets.NOSIBLE_API_KEY }}
      LLM_API_KEY: ${{ secrets.LLM_API_KEY }}
    steps:
      - uses: actions/checkout@v3
      - name: Install uv and set the python version
        uses: astral-sh/setup-uv@v5
        with:
          python-version: ${{ matrix.python-version }}
      - name: Create venv
        run: uv venv
      - name: Install project and dependencies
        run: uv pip install -r docs/requirements.txt
      - name: Install pytest and pytest-doctestplus
        run: uv pip install pytest pytest-doctestplus
      - name: Run tests
        run: uv run pytest --maxfail=1 --disable-warnings -q

  build:
    name: Build distribution
    runs-on: ubuntu-latest
    needs: test
    if: ${{ needs.test.result == 'success' }}

    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@v5

      - name: Build packages
        run: uv build

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish:
    name: Publish to PyPI
    runs-on: ubuntu-latest
    needs: build
    # Only publish to PyPi on the 'main' branch
    if: ${{ github.ref == 'refs/heads/main' && needs.build.result == 'success' }}
    environment:
      name: pypi
      url: https://pypi.org/project/nosible
    permissions:
      id-token: write
    steps:
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
