name: CI & Publish

on:
  push:
  pull_request:

jobs:
  record:
    name: Record HTTP interactions (and save cache)
    runs-on: ubuntu-latest
    env:
      NOSIBLE_API_KEY: ${{ secrets.NOSIBLE_API_KEY }}
      LLM_API_KEY:     ${{ secrets.LLM_API_KEY }}
    steps:
      - name: Check out code
        uses: actions/checkout@v4

      # 1) Restore any existing cache for THIS OS
      - name: Restore HTTP cache
        uses: actions/cache@v4
        id: cache
        with:
          path: http_tests_cache.sqlite
          key: nosible-http-cache
          enableCrossOsArchive: true
          restore-keys: |
            nosible-http-cache-

      - name: Install uv & Python 3.12
        uses: astral-sh/setup-uv@v6
        with:
          python-version: 3.12
          enable-cache: true

      - name: Create virtualenv
        run: uv venv

      - name: Install deps & run in record mode
        run: |
          uv pip install -r docs/requirements.txt
          uv pip install pytest pytest-doctestplus requests-cache
          uv run pytest --maxfail=1 --disable-warnings -q

      # 2) Save (or update) the cache under the same key
      - name: Save HTTP cache
        uses: actions/cache@v4
        with:
          path: http_tests_cache.sqlite
          key: nosible-http-cache
          enableCrossOsArchive: true

  test:
    name: Test on ${{ matrix.os }} / Python ${{ matrix.python-version }}
    needs: record
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: true
      matrix:
        os: [ubuntu-latest, macos-latest, windows-latest]
        python-version: ["3.9", "3.12"]
    env:
      NOSIBLE_API_KEY: ${{ secrets.NOSIBLE_API_KEY }}
      LLM_API_KEY:     ${{ secrets.LLM_API_KEY }}
    steps:
      - uses: actions/checkout@v4

      # restore the cache that record just saved (scoped by OS)
      - name: Restore HTTP cache
        uses: actions/cache@v4
        id: cache
        with:
          path: http_tests_cache.sqlite
          key: nosible-http-cache
          enableCrossOsArchive: true
          restore-keys: |
            nosible-http-cache-

      # fail fast if no exact cache hit
      - name: Fail on cache miss
        if: steps.cache.outputs.cache-hit != 'true'
        run: exit 1

      - name: Install uv & set Python
        uses: astral-sh/setup-uv@v6
        with:
          python-version: ${{ matrix.python-version }}
          enable-cache: true

      - name: Create venv
        run: uv venv

      - name: Install project deps
        run: uv pip install -r docs/requirements.txt

      - name: Install test deps
        run: uv pip install pytest pytest-doctestplus requests-cache

      - name: Run tests
        run: uv run pytest --maxfail=1 --disable-warnings -q

  build:
    name: Build distribution
    needs: test
    runs-on: ubuntu-latest
    if: ${{ needs.test.result == 'success' }}
    steps:
      - uses: actions/checkout@v4
        with: 
          persist-credentials: false
      - name: Install uv
        uses: astral-sh/setup-uv@v6
        with: 
          enable-cache: true
      - name: Build packages
        run: uv build
      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: python-package-distributions
          path: dist/

  publish:
    name: Publish to PyPI
    needs: build
    runs-on: ubuntu-latest
    if: ${{ github.ref == 'refs/heads/main' && needs.build.result == 'success' }}
    environment:
      name: pypi
      url: https://pypi.org/project/nosible
    permissions:
      id-token: write
    steps:
      - name: Download distributions
        uses: actions/download-artifact@v4
        with:
          name: python-package-distributions
          path: dist/
      - name: Publish to PyPI
        uses: pypa/gh-action-pypi-publish@release/v1
        with:
          pypi_token: ${{ secrets.PYPI_API_TOKEN }}
