name: Windows Tests

on:
  workflow_run:
    workflows:
      - MacOS Tests
    types:
      - completed
    conclusion: success

jobs:
  test:
    runs-on: windows-latest

    env:
      NOSIBLE_API_KEY: ${{ secrets.NOSIBLE_API_KEY }}
      LLM_API_KEY: ${{ secrets.LLM_API_KEY }}

    strategy:
      fail-fast: false
      matrix:
        python-version: ['3.9', '3.12']

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install test dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pytest pytest-doctestplus
          pip install -r docs/requirements.txt
      - name: Run tests
        run: pytest --maxfail=1 --disable-warnings -q